# Generated by Django 4.0.5 on 2022-06-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Museum Paintings'), ('P', 'Painting Fortfolio')], max_length=2)),
                ('product_image', models.ImageField(upload_to='producting')),
            ],
        ),
    ]
