# Generated by Django 4.0.5 on 2022-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_freedomar_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='musicali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instru_image', models.ImageField(upload_to='producting')),
            ],
        ),
    ]
