# Generated by Django 4.0.5 on 2022-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_musicali_type_musicali_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('W', ' Weaving'), ('P', ' Printing'), ('E', 'Embroidery')], max_length=3)),
                ('image', models.ImageField(upload_to='producting')),
            ],
        ),
    ]
